"""
Data models — Pydantic models for type safety and validation.

Models:
- AccountInfo: MT5 account state
- SymbolInfo: Symbol specifications
- Signal: Trading signal from SMC engine
- Trade: Executed trade record
- DailyPnL: Daily performance tracking
- Config models: Typed config classes
"""

from __future__ import annotations

from dataclasses import field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─── Enums ────────────────────────────────────────────────────

class Direction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class SignalType(str, Enum):
    OB_PULLBACK = "OB_PULLBACK"
    FVG_FILL = "FVG_FILL"
    LIQUIDITY_SWEEP = "LIQUIDITY_SWEEP"
    BOS_CONTINUATION = "BOS_CONTINUATION"
    H1_M5_FVG = "H1_M5_FVG"
    ML_PREDICTION = "ML_PREDICTION"


class SignalStatus(str, Enum):
    PENDING = "pending"
    TRIGGERED = "triggered"
    EXPIRED = "expired"
    CANCELLED = "cancelled"
    BLOCKED = "blocked"


class TradeStatus(str, Enum):
    OPEN = "open"
    PARTIAL_CLOSED = "partial_closed"
    CLOSED = "closed"
    EMERGENCY_CLOSED = "emergency_closed"


class MarketBias(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


class StructureType(str, Enum):
    BOS = "BOS"
    CHOCH = "CHOCH"
    NONE = "NONE"


class ChallengePhase(str, Enum):
    PHASE1 = "phase1"
    PHASE2 = "phase2"
    FUNDED = "funded"


# ─── MT5 Models ───────────────────────────────────────────────

class AccountInfo(BaseModel):
    """MT5 account information snapshot."""
    login: int = 0
    balance: float = 0.0
    equity: float = 0.0
    margin: float = 0.0
    free_margin: float = 0.0
    margin_level: float = 0.0
    profit: float = 0.0
    currency: str = "USD"
    leverage: int = 100
    server: str = ""
    name: str = ""


class SymbolInfo(BaseModel):
    """Symbol specification from MT5 or config."""
    symbol: str
    description: str = ""
    contract_size: float = 100000
    pip_size: float = 0.0001
    pip_value_per_lot: float = 10.0
    point_size: float = 0.00001
    digits: int = 5
    currency_profit: str = "USD"
    typical_spread_points: int = 10
    margin_rate: float = 0.0333
    min_volume: float = 0.01
    volume_step: float = 0.01
    max_volume: float = 100.0

    # Live data (updated per tick)
    bid: float = 0.0
    ask: float = 0.0
    spread_points: int = 0


class Tick(BaseModel):
    """Single price tick."""
    symbol: str
    bid: float
    ask: float
    time: datetime
    volume: float = 0.0


# ─── Signal Model ─────────────────────────────────────────────

class Signal(BaseModel):
    """Trading signal generated by SMC engine."""
    id: str = Field(default_factory=lambda: "")  # UUID, set at creation
    symbol: str
    direction: Direction
    signal_type: SignalType

    # Price levels
    entry_price: float
    stop_loss: float
    take_profit_1: float
    take_profit_2: float
    take_profit_3: float

    # Context
    h4_bias: MarketBias = MarketBias.NEUTRAL
    h1_structure: StructureType = StructureType.NONE
    session: str = ""

    # Risk metrics
    sl_distance_pips: float = 0.0
    risk_reward_ratio: float = 0.0  # TP1 RR

    # Meta
    timeframe: str = "M15"
    confidence: float = 50.0       # 0-100, for ML scoring
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expiry: Optional[datetime] = None
    status: SignalStatus = SignalStatus.PENDING


# ─── Trade Model ──────────────────────────────────────────────

class Trade(BaseModel):
    """Executed trade record."""
    id: str = ""                   # Internal UUID
    ticket: int = 0                # MT5 order ticket
    signal_id: str = ""            # Source signal

    symbol: str
    direction: Direction
    lot_size: float

    # Prices
    entry_price: float
    stop_loss: float
    take_profit_1: float = 0.0
    take_profit_2: float = 0.0
    take_profit_3: float = 0.0

    # State
    current_sl: float = 0.0       # Current SL (may be moved to BE/trailing)
    remaining_lot: float = 0.0    # Remaining after partial closes
    tp1_hit: bool = False
    tp2_hit: bool = False
    tp3_hit: bool = False
    breakeven_applied: bool = False
    trailing_active: bool = False

    # Timing
    open_time: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    close_time: Optional[datetime] = None

    # Result
    close_price: float = 0.0
    pnl: float = 0.0
    pnl_pips: float = 0.0
    status: TradeStatus = TradeStatus.OPEN

    # Context
    session: str = ""
    signal_type: str = ""


# ─── Daily PnL Model ─────────────────────────────────────────

class DailyPnL(BaseModel):
    """Daily performance record."""
    date: str                      # YYYY-MM-DD
    starting_balance: float
    ending_balance: float = 0.0
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    max_equity: float = 0.0
    min_equity: float = 0.0
    trade_count: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    request_count: int = 0

    @property
    def net_pnl(self) -> float:
        return self.realized_pnl + self.unrealized_pnl

    @property
    def is_positive(self) -> bool:
        return self.realized_pnl > 0


# ─── FTMO Challenge Progress ─────────────────────────────────

class ChallengeProgress(BaseModel):
    """Track FTMO challenge progress."""
    phase: ChallengePhase
    initial_balance: float
    current_balance: float = 0.0
    current_equity: float = 0.0

    # Target
    profit_target: float = 0.0
    profit_target_pct: float = 0.0
    current_profit: float = 0.0
    current_profit_pct: float = 0.0

    # Limits
    max_daily_loss: float = 0.0
    today_pnl: float = 0.0
    max_overall_loss: float = 0.0
    overall_drawdown: float = 0.0

    # Best day
    best_day_profit: float = 0.0
    total_positive_profit: float = 0.0
    best_day_pct: float = 0.0

    # Trading days
    trading_days: int = 0
    min_trading_days: int = 4

    # Status
    is_daily_limit_breached: bool = False
    is_overall_limit_breached: bool = False
    is_passed: bool = False


# ─── Config Models ────────────────────────────────────────────

class PairConfig(BaseModel):
    """Per-pair trading configuration."""
    symbol: str
    enabled: bool = True
    timeframes: dict = {"bias": "H4", "structure": "H1", "entry": "M15"}
    max_spread_points: int = 30
    min_volume: float = 0.01
    volume_step: float = 0.01


class SessionConfig(BaseModel):
    """Trading session configuration."""
    start: str          # "HH:MM" UTC
    end: str            # "HH:MM" UTC
    auto_trade: bool = True


class RiskConfig(BaseModel):
    """Risk management configuration."""
    risk_per_trade: float = 0.01
    max_concurrent_trades: int = 3
    max_daily_trades: int = 8
    max_correlation_trades: int = 2
    max_lot_size: float = 1.0


class StrategyConfig(BaseModel):
    """Strategy parameters."""
    swing_length: int = 10
    ob_lookback: int = 20
    fvg_min_size_pips: float = 5.0
    sl_buffer_pips: float = 5.0
    tp_ratios: list[float] = [1.5, 2.0, 3.0]
    tp_portions: list[float] = [0.50, 0.30, 0.20]
    breakeven_at_tp1: bool = True
    trailing_after_tp2: bool = True
    trailing_distance_pips: float = 20.0
    signal_expiry_minutes: int = 60
